name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  js-test-and-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        with:
          rust-components: rustfmt

      - run: npm install
      - run: deno fmt --check
      - run: deno lint
      - run: npm run type-check
      - run: npm run test

  rust-linter:
    runs-on: windows-2025
    steps:
      - uses: ./.github/actions/setup

      - name: Format
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Linter
        run: |-
          rustup component add clippy
          cargo clippy --locked --all-targets -- -D warnings

  rust-test:
    runs-on: windows-2025
    steps:
      - uses: ./.github/actions/setup
        with:
          cache-key-prefix: rust-test

      - run: cargo test --locked --verbose
