name: Nightly

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "documentation/**"
      - ".github/**"
      - "crowdin.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    uses: ./.github/workflows/ci.yml

  update-tag:
    needs: continuous-integration
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.gen-version.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --tags --prune

      - name: Create or update 'nightly' tag (force overwrite)
        run: |
          git tag -f nightly
          git push origin --force --tags

      - name: Generate Version
        id: gen-version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            const currentVersion = packageJson.version;

            const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
            const nightlyVersion = `${currentVersion}+${timestamp}`;

            return nightlyVersion;

  build:
    needs:
      - update-tag
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-2025"
            target: "x86_64-pc-windows-msvc"
          - platform: "windows-2025"
            target: "aarch64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-09-12
          targets: ${{ matrix.target }}
      - run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: nightly-build-${{ matrix.platform }}-${{ matrix.target }}

      - name: Install frontend dependencies
        run: npm install

      - name: Install MSIX dependencies
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: pwsh
        run: |
          winget upgrade winget --accept-package-agreements --accept-source-agreements --disable-interactivity --force || Write-Output "Ignoring winget update failure"
          winget install --id Microsoft.DotNet.AspNetCore.8 --accept-package-agreements --accept-source-agreements --force
          winget install --id Microsoft.DotNet.DesktopRuntime.8 --accept-package-agreements --accept-source-agreements --force
          winget install --id MarcinOtorowski.MSIXHero --accept-package-agreements --accept-source-agreements --force


      - name: Set Version
        run: |
          npm run versionish -- --version ${{ needs.update-tag.outputs.nightly-version }}

      # If build fails we will be without a nightly build until the next push or workflow_dispatch
      - name: Build
        run: npx tauri build --no-bundle --ci --target ${{ matrix.target }}

      - name: Bundle
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: npx tauri bundle --ci --target ${{ matrix.target }}

      - name: Bundle MSIX
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: npx tsx scripts/bundle.msix.ts --target ${{ matrix.target }}

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-bundles-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/bundle

  merge-artifacts:
    needs:
      - update-tag
      - build
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-merged.outputs.artifact-id }}
    steps:
      - name: Merge artifacts
        id: upload-merged
        uses: actions/upload-artifact/merge@v4
        with:
          name: build-bundles
          pattern: build-bundles-*
          delete-merged: true

  sign-and-upload:
    needs:
      - update-tag
      - merge-artifacts
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Submit to SignPath
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: 1a9e9b37-229a-4540-a639-137deebee4e1
          project-slug: seelen-ui
          signing-policy-slug: test-signing
          github-artifact-id: "${{ needs.merge-artifacts.outputs.artifact-id }}"
          output-artifact-directory: target/release/signed-bundle

      - name: Upload Signed Installers to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Seelen UI Nightly
          prerelease: true
          files: target/release/signed-bundle/**/*

  remove-old-artifacts:
    needs:
      - update-tag
      - sign-and-upload
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Remove Signatures and Old Artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tagName = 'nightly';
            const nightlyVersion = ${{ needs.update-tag.outputs.nightly-version }};
            console.info(`nightlyVersion: ${nightlyVersion}`);

            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName,
            });

            const result = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
            });

            // Use Promise.all for parallel deletion
            const deletions = result.data
              .filter(asset => {
                if (asset.name.endsWith('.json')) return false;
                return !asset.name.includes(nightlyVersion) || asset.name.endsWith('.sig');
              })
              .map(asset => {
                console.info(`deleting ${asset.name}`);
                return github.rest.repos.deleteReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  asset_id: asset.id,
                });
              });

            await Promise.all(deletions);
